version: '3.8'
services:
  indexer:
    build: .
    env_file: .env.testnet
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=indexer_testnet
    volumes:
      - postgres_testnet_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_testnet_data: 