version: '3.8'

services:
  indexer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/indexer
      - LOG_LEVEL=info
      - START_BLOCK=0
      - POLL_INTERVAL_MS=1000
      - CLEAR_DATA_ON_START=false
      - STATUS_SERVER_PORT=3000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=indexer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 