version: '3.8'
services:
  indexer:
    build: .
    env_file: .env.mainnet
    ports:
      - "3002:3000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data   

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=indexer_mainnet
    volumes:
      - postgres_mainnet_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres_mainnet_data: 